use super::{BindingDefault, BindingProjection as Projection, RuntimePlatform::*};
use cosmol_viewer_derive::binding_contract;

binding_contract! {
    pub static BINDING_CONTRACT = [
        {
            semantic_id: "Viewer.render", rust: crate::NativeGuiViewer::render,
            signature: fn(scene: &crate::scene::Scene, width: f32, height: f32) -> Result<crate::NativeGuiViewer, crate::RenderError>,
            rust_cfg: not(target_arch = "wasm32"), receiver: none, platforms: &[Native],
            python: Projection::supported("Viewer.render", &[Native, Notebook]),
            javascript: Projection::supported("Viewer.render", &[Browser]).with_notebook("Viewer.renderNotebook", None),
            notes: "Browser initialization is async and receives a typed Scene plus dimensions. Notebook payload startup is a separate internal endpoint.",
        },
        {
            semantic_id: "Viewer.play", rust: crate::NativeGuiViewer::play,
            signature: fn(animation: crate::scene::Animation, width: f32, height: f32) -> Result<crate::NativeGuiViewer, crate::RenderError>,
            rust_cfg: not(target_arch = "wasm32"), receiver: none, platforms: &[Native],
            python: Projection::supported("Viewer.play", &[Native, Notebook]),
            javascript: Projection::supported("Viewer.play", &[Browser]).with_notebook("Viewer.playNotebook", None),
            notes: "Browser playback is async and borrows a typed Animation. Notebook payload startup is a separate internal endpoint.",
        },
        {
            semantic_id: "Viewer.update", rust: crate::NativeGuiViewer::update,
            signature: fn(viewer: &crate::NativeGuiViewer, scene: &crate::scene::Scene),
            rust_cfg: not(target_arch = "wasm32"), receiver: shared, platforms: &[Native],
            python: Projection::supported("Viewer.update", &[Native, Notebook]),
            javascript: Projection::supported("Viewer.update", &[Browser]).with_notebook("Viewer.dispatch", Some("UpdateScene")),
            notes: "Ordinary JS updates borrow a Scene directly. Notebook delivery uses one-way dispatch; submission does not confirm presentation.",
        },
        {
            semantic_id: "Viewer.set_camera_parameter_logging", rust: crate::NativeGuiViewer::set_camera_parameter_logging,
            signature: fn(viewer: &crate::NativeGuiViewer, enabled: bool),
            rust_cfg: not(target_arch = "wasm32"), receiver: shared, platforms: &[Native],
            python: Projection::supported("Viewer.set_camera_parameter_logging", &[Native, Notebook]),
            javascript: Projection::supported("Viewer.setCameraParameterLogging", &[Browser]).with_notebook("Viewer.dispatch", Some("SetCameraParameterLogging")),
            defaults: &[BindingDefault { parameter: "enabled", python: "True" }],
        },
        {
            semantic_id: "Viewer.keep_alive", rust: crate::NativeGuiViewer::keep_alive,
            signature: fn(viewer: crate::NativeGuiViewer) -> std::io::Result<()>,
            rust_cfg: not(target_arch = "wasm32"), receiver: owned, platforms: &[Native],
            python: Projection::supported("Viewer.keep_alive", &[Native]),
            javascript: Projection::unsupported("Native child-process lifecycle only; browsers must not block waiting for console input."),
            notes: "Python notebook calls raise RuntimeError. Native wait finalizes the viewer, including on errors.",
        },
        {
            semantic_id: "Viewer.take_screenshot", rust: crate::NativeGuiViewer::take_screenshot,
            signature: fn(viewer: &crate::NativeGuiViewer) -> Result<image::ImageBuffer<image::Rgba<u8>, Vec<u8>>, crate::ImageError>,
            rust_cfg: not(target_arch = "wasm32"), receiver: shared, platforms: &[Native],
            python: Projection::unsupported("Python does not currently export Viewer.take_screenshot; use Scene.to_png for static image rendering."),
            javascript: Projection::supported("Viewer.takeScreenshot", &[Browser]).with_notebook("Viewer.takeScreenshotNotebook", None),
            notes: "Browser screenshots return PNG bytes asynchronously. Only the notebook endpoint returns a compressed transport envelope.",
        },
        {
            semantic_id: "Scene.new", rust: crate::scene::Scene::new,
            signature: fn() -> crate::scene::Scene, receiver: none, platforms: &[Native, Browser],
            python: Projection::supported("Scene", &[Native, Notebook]),
            javascript: Projection::supported("Scene.new", &[Browser]),
        },
        {
            semantic_id: "Animation.new", rust: crate::scene::Animation::new,
            signature: fn(interval: f32, loops: i64, interpolate: bool) -> crate::scene::Animation,
            receiver: none, platforms: &[Native, Browser],
            python: Projection::supported("Animation", &[Native, Notebook]),
            javascript: Projection::supported("Animation.new", &[Browser]),
        },
        {
            semantic_id: "Animation.add_frame", rust: crate::scene::Animation::add_frame,
            signature: fn(animation: &mut crate::scene::Animation, frame: crate::scene::Scene),
            receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Animation.add_frame", &[Native, Notebook]),
            javascript: Projection::supported("Animation.addFrame", &[Browser]),
            notes: "JS borrows a reusable Scene handle and captures a frame snapshot, matching core animation value semantics.",
        },
        {
            semantic_id: "Scene.recenter", rust: crate::scene::Scene::recenter,
            signature: fn(scene: &mut crate::scene::Scene, center: [f32; 3]), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.recenter", &[Native, Notebook]),
            javascript: Projection::supported("Scene.recenter", &[Browser]),
        },
        {
            semantic_id: "Scene.set_scale", rust: crate::scene::Scene::set_scale,
            signature: fn(scene: &mut crate::scene::Scene, scale: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_scale", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setScale", &[Browser]),
        },
        {
            semantic_id: "Scene.set_background_color", rust: crate::scene::Scene::set_background_color::<[u8; 3]>,
            signature: fn(scene: &mut crate::scene::Scene, background_color: [u8; 3]), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_background_color", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setBackgroundColor", &[Browser]),
        },
        {
            semantic_id: "Scene.set_transparent_background", rust: crate::scene::Scene::set_transparent_background,
            signature: fn(scene: &mut crate::scene::Scene, enabled: bool), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_transparent_background", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setTransparentBackground", &[Browser]),
            defaults: &[BindingDefault { parameter: "enabled", python: "True" }],
        },
        {
            semantic_id: "Scene.set_zoom_disabled", rust: crate::scene::Scene::set_zoom_disabled,
            signature: fn(scene: &mut crate::scene::Scene, disabled: bool), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_zoom_disabled", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setZoomDisabled", &[Browser]),
            defaults: &[BindingDefault { parameter: "disabled", python: "True" }],
        },
        {
            semantic_id: "Scene.set_auto_rotate", rust: crate::scene::Scene::set_auto_rotate,
            signature: fn(scene: &mut crate::scene::Scene, enabled: bool, speed: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_auto_rotate", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setAutoRotate", &[Browser]),
            defaults: &[BindingDefault { parameter: "enabled", python: "True" }, BindingDefault { parameter: "speed", python: "20.0" }],
        },
        {
            semantic_id: "Scene.set_depth_cue", rust: crate::scene::Scene::set_depth_cue,
            signature: fn(scene: &mut crate::scene::Scene, enabled: bool), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_depth_cue", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setDepthCue", &[Browser]),
            defaults: &[BindingDefault { parameter: "enabled", python: "True" }],
        },
        {
            semantic_id: "Scene.set_depth_cue_range", rust: crate::scene::Scene::set_depth_cue_range,
            signature: fn(scene: &mut crate::scene::Scene, start: f32, end: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_depth_cue_range", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setDepthCueRange", &[Browser]),
        },
        {
            semantic_id: "Scene.set_depth_cue_color", rust: crate::scene::Scene::set_depth_cue_color::<[u8; 3]>,
            signature: fn(scene: &mut crate::scene::Scene, color: [u8; 3]), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_depth_cue_color", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setDepthCueColor", &[Browser]),
        },
        {
            semantic_id: "Scene.use_black_background", rust: crate::scene::Scene::use_black_background,
            signature: fn(scene: &mut crate::scene::Scene), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.use_black_background", &[Native, Notebook]),
            javascript: Projection::supported("Scene.useBlackBackground", &[Browser]),
        },
        {
            semantic_id: "Scene.set_camera_view", rust: crate::scene::Scene::set_camera_view,
            signature: fn(scene: &mut crate::scene::Scene, azimuth: f32, elevation: f32, roll: f32, distance: f32, target: [f32; 3], fov: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_camera_view", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setCameraView", &[Browser]),
            // PyO3 exposes the array-valued target default as Ellipsis, not a Python literal.
            defaults: &[BindingDefault { parameter: "azimuth", python: "0.0" }, BindingDefault { parameter: "elevation", python: "0.0" }, BindingDefault { parameter: "roll", python: "0.0" }, BindingDefault { parameter: "distance", python: "35.0" }, BindingDefault { parameter: "fov", python: "15.0" }],
        },
        {
            semantic_id: "Scene.rotate_camera", rust: crate::scene::Scene::rotate_camera,
            signature: fn(scene: &mut crate::scene::Scene, azimuth_delta: f32, elevation_delta: f32, roll_delta: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.rotate_camera", &[Native, Notebook]),
            javascript: Projection::supported("Scene.rotateCamera", &[Browser]),
            defaults: &[BindingDefault { parameter: "roll_delta", python: "0.0" }],
        },
        {
            semantic_id: "Scene.set_camera_distance", rust: crate::scene::Scene::set_camera_distance,
            signature: fn(scene: &mut crate::scene::Scene, distance: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_camera_distance", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setCameraDistance", &[Browser]),
        },
        {
            semantic_id: "Scene.set_camera_target", rust: crate::scene::Scene::set_camera_target,
            signature: fn(scene: &mut crate::scene::Scene, target: [f32; 3]), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_camera_target", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setCameraTarget", &[Browser]),
        },
        {
            semantic_id: "Scene.set_camera_fov", rust: crate::scene::Scene::set_camera_fov,
            signature: fn(scene: &mut crate::scene::Scene, fov: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_camera_fov", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setCameraFov", &[Browser]),
        },
        {
            semantic_id: "Scene.set_lighting", rust: crate::scene::Scene::set_lighting,
            signature: fn(scene: &mut crate::scene::Scene, ambient: f32, diffuse: f32, specular: f32, intensity: f32, color: glam::Vec3), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_lighting", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setLighting", &[Browser]),
            defaults: &[BindingDefault { parameter: "ambient", python: "0.55" }, BindingDefault { parameter: "diffuse", python: "0.65" }, BindingDefault { parameter: "specular", python: "1.0" }, BindingDefault { parameter: "intensity", python: "1.0" }, BindingDefault { parameter: "color", python: "None" }],
        },
        {
            semantic_id: "Scene.set_light_intensity", rust: crate::scene::Scene::set_light_intensity,
            signature: fn(scene: &mut crate::scene::Scene, intensity: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_light_intensity", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setLightIntensity", &[Browser]),
        },
        {
            semantic_id: "Scene.set_ambient_light", rust: crate::scene::Scene::set_ambient_light,
            signature: fn(scene: &mut crate::scene::Scene, intensity: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_ambient_light", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setAmbientLight", &[Browser]),
        },
        {
            semantic_id: "Scene.set_light_color", rust: crate::scene::Scene::set_light_color::<[u8; 3]>,
            signature: fn(scene: &mut crate::scene::Scene, color: [u8; 3]), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.set_light_color", &[Native, Notebook]),
            javascript: Projection::supported("Scene.setLightColor", &[Browser]),
        },
        {
            semantic_id: "Scene.remove_shape", rust: crate::scene::Scene::remove_shape,
            signature: fn(scene: &mut crate::scene::Scene, id: &str) -> Result<(), crate::scene::SceneError>, receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Scene.remove_shape", &[Native, Notebook]),
            javascript: Projection::supported("Scene.removeShape", &[Browser]),
        },
        {
            semantic_id: "Animation.set_static_scene", rust: crate::scene::Animation::set_static_scene,
            signature: fn(animation: &mut crate::scene::Animation, scene: crate::scene::Scene), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Animation.set_static_scene", &[Native, Notebook]),
            javascript: Projection::supported("Animation.setStaticScene", &[Browser]),
        },
        {
            semantic_id: "Animation.set_interval", rust: crate::scene::Animation::set_interval,
            signature: fn(animation: &mut crate::scene::Animation, interval: f32), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Animation.set_interval", &[Native, Notebook]),
            javascript: Projection::supported("Animation.setInterval", &[Browser]),
        },
        {
            semantic_id: "Animation.set_loops", rust: crate::scene::Animation::set_loops,
            signature: fn(animation: &mut crate::scene::Animation, loops: i64), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Animation.set_loops", &[Native, Notebook]),
            javascript: Projection::supported("Animation.setLoops", &[Browser]),
        },
        {
            semantic_id: "Animation.set_interpolate", rust: crate::scene::Animation::set_interpolate,
            signature: fn(animation: &mut crate::scene::Animation, interpolate: bool), receiver: mutable, platforms: &[Native, Browser],
            python: Projection::supported("Animation.set_interpolate", &[Native, Notebook]),
            javascript: Projection::supported("Animation.setInterpolate", &[Browser]),
        },
    ];
}
