[project]
name = "cosmol-viewer"
version = "0.5.0rc4"
description = "Molecular visualization tools"
authors = [{name = "95028", email = "wjt@cosmol.org"}]
readme = "README.md"

[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "build_backend"
backend-path = ["."]

[tool.maturin]
name = "cosmol_viewer"
python-packages = ["cosmol_viewer_native"]
include = [
    { path = "cosmol_viewer_native/cosmol-viewer-native*", format = "wheel" },
    { path = "build_backend.py", format = "sdist" },
    { path = "build_native_viewer.py", format = "sdist" },
    { path = "cosmol_viewer.pyi", format = "sdist" },
]

[project.urls]
Repository = "https://github.com/COSMol-repl/COSMol-viewer"
